<Type Name="KestrelCommunicationListener" FullName="Microsoft.ServiceFabric.Services.Communication.AspNetCore.KestrelCommunicationListener">
  <TypeSignature Language="C#" Value="public class KestrelCommunicationListener : Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi beforefieldinit KestrelCommunicationListener extends Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener" />
  <TypeSignature Language="DocId" Value="T:Microsoft.ServiceFabric.Services.Communication.AspNetCore.KestrelCommunicationListener" />
  <TypeSignature Language="VB.NET" Value="Public Class KestrelCommunicationListener&#xA;Inherits AspNetCoreCommunicationListener" />
  <TypeSignature Language="F#" Value="type KestrelCommunicationListener = class&#xA;    inherit AspNetCoreCommunicationListener" />
  <AssemblyInfo>
    <AssemblyName>Microsoft.ServiceFabric.AspNetCore.Kestrel</AssemblyName>
    <AssemblyVersion>6.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary>
            <span data-ttu-id="3df4f-101">Ein AspNetCore Kestrel basierte Kommunikation Listener für zustandslose oder zustandsbehaftete Service Fabric-Dienst.</span><span class="sxs-lookup"><span data-stu-id="3df4f-101">An AspNetCore Kestrel based communication listener for Service Fabric stateless or stateful service.</span></span>
            </summary>
    <remarks>To be added.</remarks>
  </Docs>
  <Members>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public KestrelCommunicationListener (System.Fabric.ServiceContext serviceContext, Func&lt;string,Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener,Microsoft.AspNetCore.Hosting.IWebHost&gt; build);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(class System.Fabric.ServiceContext serviceContext, class System.Func`3&lt;string, class Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener, class Microsoft.AspNetCore.Hosting.IWebHost&gt; build) cil managed" />
      <MemberSignature Language="DocId" Value="M:Microsoft.ServiceFabric.Services.Communication.AspNetCore.KestrelCommunicationListener.#ctor(System.Fabric.ServiceContext,System.Func{System.String,Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener,Microsoft.AspNetCore.Hosting.IWebHost})" />
      <MemberSignature Language="F#" Value="new Microsoft.ServiceFabric.Services.Communication.AspNetCore.KestrelCommunicationListener : System.Fabric.ServiceContext * Func&lt;string, Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener, Microsoft.AspNetCore.Hosting.IWebHost&gt; -&gt; Microsoft.ServiceFabric.Services.Communication.AspNetCore.KestrelCommunicationListener" Usage="new Microsoft.ServiceFabric.Services.Communication.AspNetCore.KestrelCommunicationListener (serviceContext, build)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.ServiceFabric.AspNetCore.Kestrel</AssemblyName>
        <AssemblyVersion>6.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="serviceContext" Type="System.Fabric.ServiceContext" />
        <Parameter Name="build" Type="System.Func&lt;System.String,Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener,Microsoft.AspNetCore.Hosting.IWebHost&gt;" />
      </Parameters>
      <Docs>
        <param name="serviceContext"><span data-ttu-id="3df4f-102">Der Kontext des Diensts für die Kommunikation Listener erstellt wird.</span><span class="sxs-lookup"><span data-stu-id="3df4f-102">The context of the service for which this communication listener is being constructed.</span></span></param>
        <param name="build"><span data-ttu-id="3df4f-103">Delegieren zum Erstellen von Microsoft.AspNetCore.Hosting.IWebHost, Endpunkt-Url, die vom Listener generiert erhält als Eingabe für dieses Delegaten.</span><span class="sxs-lookup"><span data-stu-id="3df4f-103">Delegate to build Microsoft.AspNetCore.Hosting.IWebHost, endpoint url generated by the listener is given as input to this delegate.</span></span>
            <span data-ttu-id="3df4f-104">Dies bietet die Flexibilität, die Url vor dem Erstellen von Microsoft.AspNetCore.Hosting.IWebHost bei Bedarf zu ändern.</span><span class="sxs-lookup"><span data-stu-id="3df4f-104">This gives the flexibility to change the url before creating Microsoft.AspNetCore.Hosting.IWebHost if needed.</span></span></param>
        <summary>
            <span data-ttu-id="3df4f-105">Erstellt eine AspNetCore Kestrel basierend Kommunikation Listener eine Standardadresse mit HTTP-Protokoll und Port 0.</span><span class="sxs-lookup"><span data-stu-id="3df4f-105">Constructs a AspNetCore Kestrel based communication listener using a default address with http protocol and port 0.</span></span>
            <span data-ttu-id="3df4f-106">Kestrel wird an einen Port nicht angegeben, die dynamisch binden, wenn Port 0 in der Url angegeben ist.</span><span class="sxs-lookup"><span data-stu-id="3df4f-106">Kestrel will dynamically bind to an unspecified, available port when port 0 is specified in url.</span></span>
            </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public KestrelCommunicationListener (System.Fabric.ServiceContext serviceContext, string endpointName, Func&lt;string,Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener,Microsoft.AspNetCore.Hosting.IWebHost&gt; build);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(class System.Fabric.ServiceContext serviceContext, string endpointName, class System.Func`3&lt;string, class Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener, class Microsoft.AspNetCore.Hosting.IWebHost&gt; build) cil managed" />
      <MemberSignature Language="DocId" Value="M:Microsoft.ServiceFabric.Services.Communication.AspNetCore.KestrelCommunicationListener.#ctor(System.Fabric.ServiceContext,System.String,System.Func{System.String,Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener,Microsoft.AspNetCore.Hosting.IWebHost})" />
      <MemberSignature Language="F#" Value="new Microsoft.ServiceFabric.Services.Communication.AspNetCore.KestrelCommunicationListener : System.Fabric.ServiceContext * string * Func&lt;string, Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener, Microsoft.AspNetCore.Hosting.IWebHost&gt; -&gt; Microsoft.ServiceFabric.Services.Communication.AspNetCore.KestrelCommunicationListener" Usage="new Microsoft.ServiceFabric.Services.Communication.AspNetCore.KestrelCommunicationListener (serviceContext, endpointName, build)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.ServiceFabric.AspNetCore.Kestrel</AssemblyName>
        <AssemblyVersion>6.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="serviceContext" Type="System.Fabric.ServiceContext" />
        <Parameter Name="endpointName" Type="System.String" />
        <Parameter Name="build" Type="System.Func&lt;System.String,Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener,Microsoft.AspNetCore.Hosting.IWebHost&gt;" />
      </Parameters>
      <Docs>
        <param name="serviceContext"><span data-ttu-id="3df4f-107">Der Kontext des Diensts für die Kommunikation Listener erstellt wird.</span><span class="sxs-lookup"><span data-stu-id="3df4f-107">The context of the service for which this communication listener is being constructed.</span></span></param>
        <param name="endpointName"><span data-ttu-id="3df4f-108">Name des endpunktressource definiert im Dienstmanifest, die verwendet werden soll, um die Adresse für den Listener zu erstellen.</span><span class="sxs-lookup"><span data-stu-id="3df4f-108">Name of endpoint resource defined in service manifest that should be used to create the address for listener.</span></span>
            <span data-ttu-id="3df4f-109">Protokoll und in diesen Endpunkt angegebenen Port wird verwendet, um die Url zu erstellen.</span><span class="sxs-lookup"><span data-stu-id="3df4f-109">Protocol and port specified in this endpoint is used to create the url.</span></span>
            <span data-ttu-id="3df4f-110">Wenn die EndpointName null ist, wird eine Standardadresse mit HTTP-Protokoll und Port 0 verwendet werden.</span><span class="sxs-lookup"><span data-stu-id="3df4f-110">If the endpointName is null, a default address with http protocol and port 0 will be used.</span></span>
            <span data-ttu-id="3df4f-111">Kestrel wird an einen Port nicht angegeben, die dynamisch binden, wenn Port 0 in der Url angegeben ist.</span><span class="sxs-lookup"><span data-stu-id="3df4f-111">Kestrel will dynamically bind to an unspecified, available port when port 0 is specified in url.</span></span>
            <span data-ttu-id="3df4f-112">Wenn der angegebene EndpointName im Dienstmanifest nicht gefunden wird, wird eine InvalidOperationException, der angibt, das ausgelöst.</span><span class="sxs-lookup"><span data-stu-id="3df4f-112">If the specified endpointName is not found in service manifest, an InvalidOperationException indicating this will be thrown.</span></span></param>
        <param name="build"><span data-ttu-id="3df4f-113">Delegieren zum Erstellen von Microsoft.AspNetCore.Hosting.IWebHost, Endpunkt-Url, die vom Listener generiert erhält als Eingabe für dieses Delegaten.</span><span class="sxs-lookup"><span data-stu-id="3df4f-113">Delegate to build Microsoft.AspNetCore.Hosting.IWebHost, endpoint url generated by the listener is given as input to this delegate.</span></span>
            <span data-ttu-id="3df4f-114">Dies bietet die Flexibilität, die Url vor dem Erstellen von Microsoft.AspNetCore.Hosting.IWebHost bei Bedarf zu ändern.</span><span class="sxs-lookup"><span data-stu-id="3df4f-114">This gives the flexibility to change the url before creating Microsoft.AspNetCore.Hosting.IWebHost if needed.</span></span></param>
        <summary>
            <span data-ttu-id="3df4f-115">Erstellt eine AspNetCore Kestrel basierend Kommunikation Listener.</span><span class="sxs-lookup"><span data-stu-id="3df4f-115">Constructs a AspNetCore Kestrel based communication listener.</span></span>
            </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName="GetListenerUrl">
      <MemberSignature Language="C#" Value="protected override string GetListenerUrl ();" />
      <MemberSignature Language="ILAsm" Value=".method familyhidebysig virtual instance string GetListenerUrl() cil managed" />
      <MemberSignature Language="DocId" Value="M:Microsoft.ServiceFabric.Services.Communication.AspNetCore.KestrelCommunicationListener.GetListenerUrl" />
      <MemberSignature Language="VB.NET" Value="Protected Overrides Function GetListenerUrl () As String" />
      <MemberSignature Language="F#" Value="override this.GetListenerUrl : unit -&gt; string" Usage="kestrelCommunicationListener.GetListenerUrl " />
      <MemberType>Method</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.ServiceFabric.AspNetCore.Kestrel</AssemblyName>
        <AssemblyVersion>6.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Parameters />
      <Docs>
        <summary>
            <span data-ttu-id="3df4f-116">Ruft die Url für den Listener ab.</span><span class="sxs-lookup"><span data-stu-id="3df4f-116">Gets url for the listener.</span></span> <span data-ttu-id="3df4f-117">Listener-Url wird erstellt, mit den Filtern EndpointName, die in den Konstruktor übergeben.</span><span class="sxs-lookup"><span data-stu-id="3df4f-117">Listener url is created using the endpointName passed in the constructor.</span></span>
            <span data-ttu-id="3df4f-118">Wenn die EndpointName null war, wird eine standardmäßige Url mit HTTP-Protokoll und Port 0 (null) zurückgegeben.</span><span class="sxs-lookup"><span data-stu-id="3df4f-118">If the endpointName was null, a default url with http protocol and port zero is returned.</span></span>
            </summary>
        <returns><span data-ttu-id="3df4f-119">die URL für den Listener.</span><span class="sxs-lookup"><span data-stu-id="3df4f-119">url for the listener.</span></span></returns>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
  </Members>
</Type>