<Type Name="MsalUiRequiredException" FullName="Microsoft.Identity.Client.MsalUiRequiredException">
  <TypeSignature Language="C#" Value="public class MsalUiRequiredException : Microsoft.Identity.Client.MsalException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi beforefieldinit MsalUiRequiredException extends Microsoft.Identity.Client.MsalException" />
  <TypeSignature Language="DocId" Value="T:Microsoft.Identity.Client.MsalUiRequiredException" />
  <TypeSignature Language="VB.NET" Value="Public Class MsalUiRequiredException&#xA;Inherits MsalException" />
  <TypeSignature Language="F#" Value="type MsalUiRequiredException = class&#xA;    inherit MsalException" />
  <AssemblyInfo>
    <AssemblyName>Microsoft.Identity.Client</AssemblyName>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>Microsoft.Identity.Client.MsalException</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary>
            <span data-ttu-id="45876-101">Diese Ausnahmeklasse besteht darin Entwickler zu informieren, die Interaktion mit der Benutzeroberfläche für die erfolgreiche Authentifizierung erforderlich ist.</span><span class="sxs-lookup"><span data-stu-id="45876-101">This exception class is to inform developers that UI interaction is required for authentication to succeed.</span></span>
            </summary>
    <remarks>To be added.</remarks>
  </Docs>
  <Members>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public MsalUiRequiredException (string errorCode);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string errorCode) cil managed" />
      <MemberSignature Language="DocId" Value="M:Microsoft.Identity.Client.MsalUiRequiredException.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (errorCode As String)" />
      <MemberSignature Language="F#" Value="new Microsoft.Identity.Client.MsalUiRequiredException : string -&gt; Microsoft.Identity.Client.MsalUiRequiredException" Usage="new Microsoft.Identity.Client.MsalUiRequiredException errorCode" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Identity.Client</AssemblyName>
        <AssemblyVersion>1.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="errorCode" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="errorCode">
            <span data-ttu-id="45876-102">Der Fehlercode vom Dienst zurückgegeben wurde oder vom Client generiert.</span><span class="sxs-lookup"><span data-stu-id="45876-102">The error code returned by the service or generated by client.</span></span> <span data-ttu-id="45876-103">Dies ist der Code, den Sie für die Ausnahmebehandlung auf verlassen können.</span><span class="sxs-lookup"><span data-stu-id="45876-103">This is the code you can rely on for exception handling.</span></span>
            </param>
        <summary>
            <span data-ttu-id="45876-104">Initialisiert eine neue Instanz der Exception-Klasse mit einem angegebenen Fehlercode.</span><span class="sxs-lookup"><span data-stu-id="45876-104">Initializes a new instance of the exception class with a specified error code.</span></span>
            </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public MsalUiRequiredException (string errorCode, string errorMessage);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string errorCode, string errorMessage) cil managed" />
      <MemberSignature Language="DocId" Value="M:Microsoft.Identity.Client.MsalUiRequiredException.#ctor(System.String,System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (errorCode As String, errorMessage As String)" />
      <MemberSignature Language="F#" Value="new Microsoft.Identity.Client.MsalUiRequiredException : string * string -&gt; Microsoft.Identity.Client.MsalUiRequiredException" Usage="new Microsoft.Identity.Client.MsalUiRequiredException (errorCode, errorMessage)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Identity.Client</AssemblyName>
        <AssemblyVersion>1.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="errorCode" Type="System.String" />
        <Parameter Name="errorMessage" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="errorCode">
            <span data-ttu-id="45876-105">Der Fehlercode vom Dienst zurückgegeben wurde oder vom Client generiert.</span><span class="sxs-lookup"><span data-stu-id="45876-105">The error code returned by the service or generated by client.</span></span> <span data-ttu-id="45876-106">Dies ist der Code, den Sie für die Ausnahmebehandlung auf verlassen können.</span><span class="sxs-lookup"><span data-stu-id="45876-106">This is the code you can rely on for exception handling.</span></span>
            </param>
        <param name="errorMessage"><span data-ttu-id="45876-107">Die Fehlermeldung, in der die Ursache der Ausnahme erklärt wird.</span><span class="sxs-lookup"><span data-stu-id="45876-107">The error message that explains the reason for the exception.</span></span></param>
        <summary>
            <span data-ttu-id="45876-108">Initialisiert eine neue Instanz der Exception-Klasse mit einem angegebenen Fehlercode und eine Fehlermeldung an.</span><span class="sxs-lookup"><span data-stu-id="45876-108">Initializes a new instance of the exception class with a specified error code and error message.</span></span>
            </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public MsalUiRequiredException (string errorCode, string errorMessage, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string errorCode, string errorMessage, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:Microsoft.Identity.Client.MsalUiRequiredException.#ctor(System.String,System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (errorCode As String, errorMessage As String, innerException As Exception)" />
      <MemberSignature Language="F#" Value="new Microsoft.Identity.Client.MsalUiRequiredException : string * string * Exception -&gt; Microsoft.Identity.Client.MsalUiRequiredException" Usage="new Microsoft.Identity.Client.MsalUiRequiredException (errorCode, errorMessage, innerException)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Identity.Client</AssemblyName>
        <AssemblyVersion>1.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="errorCode" Type="System.String" />
        <Parameter Name="errorMessage" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="errorCode">
            <span data-ttu-id="45876-109">Der Fehlercode vom Dienst zurückgegeben wurde oder vom Client generiert.</span><span class="sxs-lookup"><span data-stu-id="45876-109">The error code returned by the service or generated by client.</span></span> <span data-ttu-id="45876-110">Dies ist der Code, den Sie für die Ausnahmebehandlung auf verlassen können.</span><span class="sxs-lookup"><span data-stu-id="45876-110">This is the code you can rely on for exception handling.</span></span>
            </param>
        <param name="errorMessage"><span data-ttu-id="45876-111">Die Fehlermeldung, in der die Ursache der Ausnahme erklärt wird.</span><span class="sxs-lookup"><span data-stu-id="45876-111">The error message that explains the reason for the exception.</span></span></param>
        <param name="innerException"><span data-ttu-id="45876-112">Stellt die Ursache der Ausnahme.</span><span class="sxs-lookup"><span data-stu-id="45876-112">Represents the root cause of the exception.</span></span></param>
        <summary>
            <span data-ttu-id="45876-113">Initialisiert eine neue Instanz der Exception-Klasse mit einem angegebenen Fehlercode, Fehlermeldung und inneren Ausnahme, der angibt, der Ursache.</span><span class="sxs-lookup"><span data-stu-id="45876-113">Initializes a new instance of the exception class with a specified error code, error message and inner exception indicating the root cause.</span></span>
            </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName="InvalidGrantError">
      <MemberSignature Language="C#" Value="public static readonly string InvalidGrantError;" />
      <MemberSignature Language="ILAsm" Value=".field public static initonly string InvalidGrantError" />
      <MemberSignature Language="DocId" Value="F:Microsoft.Identity.Client.MsalUiRequiredException.InvalidGrantError" />
      <MemberSignature Language="VB.NET" Value="Public Shared ReadOnly InvalidGrantError As String " />
      <MemberSignature Language="F#" Value=" staticval mutable InvalidGrantError : string" Usage="Microsoft.Identity.Client.MsalUiRequiredException.InvalidGrantError" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Identity.Client</AssemblyName>
        <AssemblyVersion>1.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
            <span data-ttu-id="45876-114">Standard OAuth2-Protokoll-Fehlercode.</span><span class="sxs-lookup"><span data-stu-id="45876-114">Standard OAuth2 protocol error code.</span></span> <span data-ttu-id="45876-115">Er gibt an, die libray, dass der Benutzer, um die Benutzeroberfläche für die erste eines neuen Tokens zu wechseln muss.</span><span class="sxs-lookup"><span data-stu-id="45876-115">It indicates to the libray that the user needs to go the UI for getting a new token.</span></span>
            </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName="NoPromptFailedError">
      <MemberSignature Language="C#" Value="public static readonly string NoPromptFailedError;" />
      <MemberSignature Language="ILAsm" Value=".field public static initonly string NoPromptFailedError" />
      <MemberSignature Language="DocId" Value="F:Microsoft.Identity.Client.MsalUiRequiredException.NoPromptFailedError" />
      <MemberSignature Language="VB.NET" Value="Public Shared ReadOnly NoPromptFailedError As String " />
      <MemberSignature Language="F#" Value=" staticval mutable NoPromptFailedError : string" Usage="Microsoft.Identity.Client.MsalUiRequiredException.NoPromptFailedError" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Identity.Client</AssemblyName>
        <AssemblyVersion>1.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
            <span data-ttu-id="45876-116">Eine von zwei Bedingungen aufgetreten ist.</span><span class="sxs-lookup"><span data-stu-id="45876-116">One of two conditions was encountered.</span></span>
            1. <span data-ttu-id="45876-117">Das Flag PromptBehavior.Never übergeben wurde und jedoch die Einschränkung konnte nicht berücksichtigt werden, da eine Benutzerinteraktion erforderlich war.</span><span class="sxs-lookup"><span data-stu-id="45876-117">The PromptBehavior.Never flag was passed and but the constraint could not be honored because user interaction was required.</span></span>
            2. <span data-ttu-id="45876-118">Fehler bei einem automatischen Webauthentifizierung, die verhindert, dass der Authentifizierungsablauf abschließen in einen kurzen genügend Zeitraums ausgeführt wurden.</span><span class="sxs-lookup"><span data-stu-id="45876-118">An error occurred during a silent web authentication that prevented the authentication flow from completing in a short enough time frame.</span></span>
            </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName="NoTokensFoundError">
      <MemberSignature Language="C#" Value="public static readonly string NoTokensFoundError;" />
      <MemberSignature Language="ILAsm" Value=".field public static initonly string NoTokensFoundError" />
      <MemberSignature Language="DocId" Value="F:Microsoft.Identity.Client.MsalUiRequiredException.NoTokensFoundError" />
      <MemberSignature Language="VB.NET" Value="Public Shared ReadOnly NoTokensFoundError As String " />
      <MemberSignature Language="F#" Value=" staticval mutable NoTokensFoundError : string" Usage="Microsoft.Identity.Client.MsalUiRequiredException.NoTokensFoundError" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Identity.Client</AssemblyName>
        <AssemblyVersion>1.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
            <span data-ttu-id="45876-119">Den Kriterien entspricht, ist keine Token gefunden.</span><span class="sxs-lookup"><span data-stu-id="45876-119">No tokens were found matching the criteria.</span></span>
            </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName="TokenCacheNullError">
      <MemberSignature Language="C#" Value="public static readonly string TokenCacheNullError;" />
      <MemberSignature Language="ILAsm" Value=".field public static initonly string TokenCacheNullError" />
      <MemberSignature Language="DocId" Value="F:Microsoft.Identity.Client.MsalUiRequiredException.TokenCacheNullError" />
      <MemberSignature Language="VB.NET" Value="Public Shared ReadOnly TokenCacheNullError As String " />
      <MemberSignature Language="F#" Value=" staticval mutable TokenCacheNullError : string" Usage="Microsoft.Identity.Client.MsalUiRequiredException.TokenCacheNullError" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Identity.Client</AssemblyName>
        <AssemblyVersion>1.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
            <span data-ttu-id="45876-120">Mit diesem Fehlercode stammt wieder aus AcquireTokenSilent aufrufen, wenn der Tokencache null-Verweis an den Anwendungskonstruktor übergeben wird</span><span class="sxs-lookup"><span data-stu-id="45876-120">This error code comes back from AcquireTokenSilent calls when null token cache reference is passed into the application constructor</span></span>
            </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName="UserNullError">
      <MemberSignature Language="C#" Value="public static readonly string UserNullError;" />
      <MemberSignature Language="ILAsm" Value=".field public static initonly string UserNullError" />
      <MemberSignature Language="DocId" Value="F:Microsoft.Identity.Client.MsalUiRequiredException.UserNullError" />
      <MemberSignature Language="VB.NET" Value="Public Shared ReadOnly UserNullError As String " />
      <MemberSignature Language="F#" Value=" staticval mutable UserNullError : string" Usage="Microsoft.Identity.Client.MsalUiRequiredException.UserNullError" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Identity.Client</AssemblyName>
        <AssemblyVersion>1.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
            <span data-ttu-id="45876-121">Mit diesem Fehlercode stammt AcquireTokenSilent Aufrufe zurück, wenn null-Benutzer in AcquireTokenSilent Aufrufe übergeben wird.</span><span class="sxs-lookup"><span data-stu-id="45876-121">This error code comes back from AcquireTokenSilent calls when null user is passed into AcquireTokenSilent calls.</span></span>
            </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
  </Members>
</Type>